### ISSUE TITLE
Allow repo name and typingsName.d.ts to differ.

### ISSUE THREAD

**Issue by Think7** [unional/generator-typings#1]
```
What is the username/repo of the package you are writing this typings for?:
Think7/typings-mongodb
```
Running the above results in the d.ts and all references to it being "typings-mongodb.d.ts"

The / official / mongodb.d.ts typing should be the same name as the library it provides typing for. If that happens to end up being mine, great! But i personally should not have a public repo called "mongodb" just to get the name to match. 

Someone might accidentally think i was talented enough to write something much fancier (mongodb) than what's actually there (just the def)!

**Comment by unional** [comment]
Haha. I need to work on the wording. Any suggestion?

What I meant to ask is the username/repo of the Target module. E.g `facebook/react`

Not your typed repo for the definition. Which is typically named as `typed-react`. 

Thanks for posting the first issue!

Keep it coming. :rose:

**Comment by Think7** [comment]
Ahhhhh, right, ok.

What about:

```
Enter the official authorName/moduleName of the new typing:
(example: "facebook/react")

Captain:Hammer$: cheesy/ontheoutside
```

**Comment by unional** [comment]
@Think7 , I reworked all the questions and add basic functionality to it. Give it a try! :rose:

**Comment by Think7** [comment]
Yessir! In iOS land. Give me a bit.. :D
